#!/usr/bin/env python3
"""Rebuild .gid/docs/issues-index.md from ISS-NNN/issue.md frontmatter."""
import re, sys
from datetime import datetime
from pathlib import Path

ROOT = Path("/Users/potato/rustclaw/.gid/issues")
OUT = Path("/Users/potato/rustclaw/.gid/docs/issues-index.md")

def parse_fm(text):
    if not text.lstrip().startswith("---"):
        return None
    lines = text.splitlines()
    if lines[0].strip() != "---":
        return None
    end = None
    for i, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            end = i
            break
    if end is None:
        return None
    fm = {}
    for line in lines[1:end]:
        m = re.match(r'^([a-zA-Z_]+):\s*(.*)$', line)
        if not m:
            continue
        k, v = m.group(1), m.group(2).strip()
        # strip wrapping quotes
        if v.startswith('"') and v.endswith('"'):
            v = v[1:-1]
        # parse list  [..., ...]
        if v.startswith("[") and v.endswith("]"):
            inner = v[1:-1]
            v = [x.strip().strip('"') for x in inner.split(",") if x.strip()]
        fm[k] = v
    return fm

issues = []
for d in sorted(ROOT.iterdir()):
    if not d.is_dir() or not d.name.startswith("ISS-"):
        continue
    f = d / "issue.md"
    if not f.exists():
        continue
    fm = parse_fm(f.read_text())
    if fm is None:
        print(f"WARN: no frontmatter {f}", file=sys.stderr)
        continue
    fm["_path"] = f"`.gid/issues/{d.name}/issue.md`"
    issues.append(fm)

PRIO_ORDER = {"P0": 0, "P1": 1, "P2": 2, "P3": 3}
def prio_key(i):
    return PRIO_ORDER.get(i.get("priority", "P3"), 99)

groups = {"open": [], "in_progress": [], "blocked": [],
          "closed": [], "wontfix": [], "superseded": []}
for i in issues:
    s = i.get("status", "open")
    groups.setdefault(s, []).append(i)
for k in groups:
    groups[k].sort(key=lambda x: (prio_key(x), x.get("id", "")))

now = datetime.now().strftime("%Y-%m-%d %H:%M")
out = []
out.append("# Issues: rustclaw")
out.append("")
out.append("> AUTO-GENERATED by project-issues skill v5. DO NOT EDIT BY HAND.")
out.append("> Source: `.gid/issues/ISS-NNN/issue.md` frontmatter.")
out.append(f"> Last rebuilt: {now}")
out.append("")
out.append(f"**Total**: {len(issues)} issues "
           f"({sum(1 for k,v in groups.items() if k in ('open','in_progress','blocked')for _ in v)} active, "
           f"{sum(1 for k,v in groups.items() if k in ('closed','wontfix','superseded'))} archived)")
out.append("")

for status_label, status_key in [
    ("Open", "open"), ("In Progress", "in_progress"), ("Blocked", "blocked"),
    ("Closed", "closed"), ("Won't Fix", "wontfix"), ("Superseded", "superseded"),
]:
    items = groups.get(status_key, [])
    if not items:
        continue
    out.append(f"## {status_label} ({len(items)})")
    out.append("")
    for i in items:
        iid = i.get("id", "?")
        title = i.get("title", "?")
        prio = i.get("priority", "P?")
        out.append(f"### {iid} [{prio}] {title}")
        meta_bits = []
        if "created" in i:    meta_bits.append(f"**Created**: {i['created']}")
        if "closed" in i:     meta_bits.append(f"**Closed**: {i['closed']}")
        if "component" in i:  meta_bits.append(f"**Component**: {i['component']}")
        if meta_bits:
            out.append("  |  ".join(meta_bits))
        if "depends_on" in i:
            deps = i["depends_on"] if isinstance(i["depends_on"], list) else [i["depends_on"]]
            out.append(f"**Blocked by**: {', '.join(deps)}")
        if "related" in i:
            rel = i["related"] if isinstance(i["related"], list) else [i["related"]]
            out.append(f"**Related**: {', '.join(rel)}")
        if "supersedes" in i:
            sup = i["supersedes"] if isinstance(i["supersedes"], list) else [i["supersedes"]]
            out.append(f"**Supersedes**: {', '.join(sup)}")
        if "superseded_by" in i:
            out.append(f"**Superseded by**: {i['superseded_by']}")
        if "note" in i:
            out.append(f"_{i['note']}_")
        out.append(f"Path: {i['_path']}")
        out.append("")

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text("\n".join(out))
print(f"Wrote {OUT} ({len(issues)} issues)")
